language: php

php:
    - 7.1

install:
    - composer install --no-interaction
    - cp .env.travis .env
    - touch database/database.sqlite
    - php artisan migrate

script:
    - php vendor/bin/phpunit
