language: php

php:
    - 7.1
    - 7.2

services:
    - redis-server
    
cache:
    directories:
        - node_modules
        - vendor

install:
    - cp .env.example .env
    - composer install --no-interaction --no-suggest --prefer-dist

script:
    - php vendor/bin/phpunit
