language: php

php:
    - 7.1

install:
    - composer install --no-interaction
    - cp .env.travis.example .env
    - php artisan key:generate
    - touch database/database.sqlite
    - php artisan migrate
    - php artisan passport:keys
    - php artisan passport:install

script:
    - php vendor/bin/phpunit
